Feature branch
TayyabKM/Hello-Microverse- pull request #1
Opened 2022-09-20 11:21 UTC by TayyabKM

2022-09-20 11:46 UTC, 1GORDON requested changes
##
## Hi @TayyabKM ✋

Good job so far!

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

- [x] Kindly add Linter files to your project. These files will enable your linter checks to pass or fail the tests. At the moment you don't have linter files.  You can find the correct [linter files](https://github.com/microverseinc/linters-config/tree/master/html-css) for this project in this link.

- [x] Kindly create a `.gitignore` in your root directory, and inside this file, add the `test.md` file. Remember that this `test.md` file is supposed to be ignored by git according to [project requirements](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md).

- [x] Kindly add a description to your Pull Request. This is where you list the tasks achieved within this milestone.
![pr description](https://user-images.githubusercontent.com/63917725/191249803-f082d8ef-6dbf-4dd3-900d-cfbda869ab05.PNG)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-20 11:46 UTC, 1GORDON commented on README.md
> +
Great job @TayyabKM 🤝

- [ ] Kindly add the correct Readme file and customize it accordingly. You can get the [readme file template](https://github.com/microverseinc/readme-template) at this link

2022-09-20 11:46 UTC, 1GORDON commented on .css
> +
Great job @TayyabKM 🤝

- [ ] Kindly remove markup from your stylesheet as this file should contain styles being applied to the markup in the HTML file.
- [ ] Also remember to give a descriptive name to your CSS file. ie `styles.css`.

2022-09-20 11:46 UTC, 1GORDON commented on .html
> +
Great job @TayyabKM 🤝

- [ ] Kindly use a better boilerplate for your HTML markup. I would suggest this option. [HTML boilerplate](https://www.freecodecamp.org/news/basic-html5-template-boilerplate-code-example/).
- [ ] You may then apply the class to your element correctly and then apply styles to this class in the stylesheet.
- [ ] Kindly give a descriptive name to your HTML file such as the `index.html` file. Your file at the moment is just a `.html`. Kindly name your file accordingly.

2022-09-20 13:02 UTC, mckent05 requested changes
Hi @TayyabKM , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which have not been addressed yet.

 ## Highlights
- Good job implementing some of the required changes ✔️ ✔️ 
 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your code.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-20 13:02 UTC, mckent05 commented on README.md
> +
- Please use the [Mciroverse readme template](https://github.com/microverseinc/readme-template/blob/master/README.md), this would help make your repo look even more professional 💯

2022-09-20 13:02 UTC, mckent05 commented on index.html
> +
- Just like the previous reviewer requested, please use a proper [HTML markup](https://www.freecodecamp.org/news/basic-html5-template-boilerplate-code-example/). Please refer to the article to read more on how that can be used. 😃 
- Since, you have a `css` file, you can do without the `style="background-color: ;"` line and link your `.css` file to your HTML file. Read more about how to do this [here](https://www.freecodecamp.org/news/basic-html5-template-boilerplate-code-example/)

2022-09-20 13:02 UTC, mckent05 commented on style.css
> +
- Your `css` file contains some invalid code, hence the linter errors. You can refer to this [article](https://www.w3schools.com/css/) to learn more about styling with `css`

2022-09-20 13:29 UTC, TayyabKM commented
"Check the comments under the review." .This is the last required change right? But I don't understand it. Would mean a lot if you could help @mckent05 .
Regards.

2022-09-21 08:34 UTC, nedjwab approved these changes
# 🟢 Project Approved! 🏆

## Hi @TayyabKM  👋

Your project is complete! ✔️ 🏁

Your code was very professional 💯

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉

 
## Highlights 🌟

- ✔️ Descriptive commmit messsages
- ✔️ Descriptive PR description
- ✔️ No linter Errors
- The code is top-notch! 💯 and have a huge potential.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-21 08:38 UTC, merged